version: '3.2'

services:
  bankapi_app:
    build:
      context: ../
      dockerfile: deployment/app.Dockerfile
    working_dir: /var/www
    depends_on:
      - bankapi_database
    command: sh deployment/app.sh
    volumes:
      - ../:/var/www
    environment:
      APP_ENV: local
      COMPOSER_ALLOW_SUPERUSER: 1
    networks:
      - default
      - bankapi-net

  bankapi_web:
   build:
     context: ../
     dockerfile: deployment/web.Dockerfile
   working_dir: /var/www
   depends_on:
     - bankapi_app
   volumes:
    - ../:/var/www
   ports:
    - 6090:80
   networks:
    - default
    - bankapi-net

  bankapi_database:
    build:
      context: ../
      dockerfile: deployment/database.Dockerfile
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - 33078:3306
    networks:
      - default

volumes:
  dbdata:

networks:
    bankapi-net:
       external: true
